name: SyncFinanceData

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: browser-actions/setup-firefox@v1
    - run: firefox --version
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Configure pip caching
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Copy master folder
      run: |-
        rsync -Rr ./ ./master/
    - name: Checkout data branch
      run: |-
        git checkout data
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./master/requirements-yahoo_finance_cron_job.txt
    - name: Copy data source
      run: |-
        mkdir -p ./master/data-output
        [ -d "./data-output/esgChart" ] && cp -r ./data-output/esgChart ./master/data-output && cp ./data-output/stock-benford-law.json ./master/data-output
    - name: Run sync Finance data
      env:
        AF_URL: ${{ secrets.AF_URL }}
        AF_TOKEN: ${{ secrets.AF_TOKEN }}
      run: |-
        python ./master/yahoo_finance_cron_job.py
